PrestaCMS\CoreBundle\Entity\BasePageRevisionBlock:
  type: mappedSuperclass
  repositoryClass: PrestaCMS\CoreBundle\Repository\PageRevisionBlockRepository
  gedmo:
    translation:
      locale: locale
      entity: PrestaCMS\CoreBundle\Entity\PageRevisionBlockTranslation
  fields:
    zone:
      type: string
      length: 128
      gedmo:
        - sortableGroup
    position:
      type: integer
      gedmo:
        - sortablePosition
    is_active:
      type: boolean
      default: false
      gedmo:
        - translatable
    is_editable:
      type: boolean
      default: false
    is_deletable:
      type: boolean
      default: false
    type:
      type: string
      length: 128
    settings:
      type: array
      gedmo:
        - translatable
  manyToOne:
    pageRevision:
      targetEntity: Application\PrestaCMS\CoreBundle\Entity\PageRevision
      inversedBy: blocks
      joinColumn:
        name: page_revision_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
