PrestaCMS\CoreBundle\Entity\BasePage:
  type: mappedSuperclass
  repositoryClass: PrestaCMS\CoreBundle\Repository\PageRepository
  gedmo:
    translation:
      locale: locale
      entity: PrestaCMS\CoreBundle\Entity\PageTranslation
    tree:
      type: nested
  fields:
    name:
      type: string
      length: 255
      gedmo:
        - translatable
    isActive:
      type: boolean
      column: is_active
      default: false
      gedmo:
        - translatable
    url:
      type: string
      length: 255
      gedmo:
        - translatable
    title:
      type: string
      length: 64
      gedmo:
        - translatable
    metaKeywords:
      type: string
      column: meta_keywords
      length: 255
      gedmo:
        - translatable
    metaDescription:
      type: string
      column: meta_description
      length: 255
      gedmo:
        - translatable
    type:
      type: string
      length: 25
    settings:
      type: array
      gedmo:
        - translatable
        
  manyToOne:
    website:
      targetEntity: Application\PrestaCMS\CoreBundle\Entity\Website
      inversedBy: pages
      joinColumn:
        name: website_id
        referencedColumnName: id
    
  
  lifecycleCallbacks: {  }
