PrestaCMS\CoreBundle\Entity\BaseThemeBlock:
  type: mappedSuperclass
  gedmo:
    translation:
      locale: locale
  fields:
    theme:
      type: string
      length: 64
    zone:
      type: string
      length: 128
      gedmo:
        - sortableGroup
    position:
      type: integer
      gedmo:
        - sortablePosition
    is_active:
      type: boolean
      default: false
      gedmo:
        - translatable
    block_type:
      type: string
      length: 128
    content:
      type: text
      gedmo:
        - translatable
  manyToOne:
    website:
      targetEntity: Application\PrestaCMS\CoreBundle\Entity\Website
      inversedBy: themeBlocks
      joinColumn:
        name: website_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
