Presta\CMSCoreBundle\Entity\BasePageRevision:
  type: mappedSuperclass
  repositoryClass: Presta\CMSCoreBundle\Repository\PageRevisionRepository
  gedmo:
    translation:
      locale: locale
      entity: Presta\CMSCoreBundle\Entity\PageRevisionTranslation
  fields:
    page_id:
      type: integer    
    template:
      type: string
      length: 64    
    created:
      type: date
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    status:
      type: string
      length: 25
      gedmo:
        - translatable
  manyToOne:
    page:
      targetEntity: Application\Presta\CMSCoreBundle\Entity\Page
      inversedBy: revisions
      joinColumn:
        name: page_id
        referencedColumnName: id   
  
  lifecycleCallbacks: {  }
