PrestaCMS\CoreBundle\Entity\BasePageBlock:
  type: mappedSuperclass
  repositoryClass: PrestaCMS\CoreBundle\Repository\PageBlockRepository
  gedmo:
    translation:
      locale: locale
      entity: PrestaCMS\CoreBundle\Entity\PageBlockTranslation
  fields:
    zone:
      type: string
      length: 128
      gedmo:
        - sortableGroup
    position:
      type: integer
      gedmo:
        - sortablePosition
    is_active:
      type: boolean
      default: false
      gedmo:
        - translatable
    block_type:
      type: string
      length: 128
    content:
      type: text
      gedmo:
        - translatable
  manyToOne:
    pageRevision:
      targetEntity: Application\PrestaCMS\CoreBundle\Entity\PageRevision
      inversedBy: blocks
      joinColumn:
        name: page_revision_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
