PrestaCMS\CoreBundle\Entity\BaseThemeBlock:
  type: mappedSuperclass
  repositoryClass: PrestaCMS\CoreBundle\Repository\ThemeBlockRepository
  gedmo:
    translation:
      locale: locale
  fields:
    theme:
      type: string
      length: 64
    zone:
      type: string
      length: 128
      gedmo:
        - sortableGroup
    position:
      type: integer
      gedmo:
        - sortablePosition
    is_active:
      type: boolean
      default: false
      gedmo:
        - translatable
    is_editable:
      type: boolean
      default: false
    is_deletable:
      type: boolean
      default: false
    type:
      type: string
      length: 128
    settings:
      type: array
#      gedmo:
#        - translatable
  manyToOne:
    website:
      targetEntity: Application\PrestaCMS\CoreBundle\Entity\Website
      inversedBy: themeBlocks
      joinColumn:
        name: website_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
