Presta\CMSCoreBundle\Entity\BasePageRevisionBlock:
  type: mappedSuperclass
#  repositoryClass: Presta\CMSCoreBundle\Repository\PageRevisionBlockRepository todo voir si on peut avoir les trad sans specific repo!
  gedmo:
    translation:
      locale: locale
      entity: Presta\CMSCoreBundle\Entity\PageRevisionBlockTranslation
  fields:
    zone:
      type: string
      length: 128
      gedmo:
        - sortableGroup
    position:
      type: integer
      gedmo:
        - sortablePosition
    is_active:
      type: boolean
      default: false
      gedmo:
        - translatable
    is_editable:
      type: boolean
      default: false
    is_deletable:
      type: boolean
      default: false
    type:
      type: string
      length: 128
    settings:
      type: array
      gedmo:
        - translatable
  manyToOne:
    pageRevision:
      targetEntity: Application\Presta\CMSCoreBundle\Entity\PageRevision
      inversedBy: blocks
      joinColumn:
        name: page_revision_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
