Presta\CMSCoreBundle\Entity\BaseWebsite:
  type: mappedSuperclass
  repositoryClass: Presta\CMSCoreBundle\Repository\WebsiteRepository
  gedmo:
    translation:
      locale: locale
      entity: Presta\CMSCoreBundle\Entity\WebsiteTranslation
  fields:        
    name:
      type: string
      length: 255
    host:
      type: string
      length: 255
      gedmo:
        - translatable
    relative_path:
      type: string
      length: 255
      gedmo:
        - translatable
    theme:
      type: string
      length: 25
      gedmo:
        - translatable
    is_active:
      type: boolean
      default: false
    is_default:
      type: boolean
      default: false
    default_locale:
      type: string
      length: 5
    available_locales:
      type: array
    
  lifecycleCallbacks: {  }
