imports:
#     - { resource: '@PrestaAssetTinymceBundle/Resources/config/config.yml' }
#     - { resource: '@PrestaSonataMediaBundle/Resources/config/config.yml' }


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~


# Assetic Configuration
assetic:
    bundles:
        - PrestaCMSCoreBundle

sonata_block:
    blocks:
        presta_cms.block.dashboard.cms:
        presta_cms.block.website.selector:

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            symfony_cmf_routing_extra.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_alias:
            demo_alias: presta_cms.page.controller:aliasAction
        controllers_by_class:
            Presta\CMSCoreBundle\Document\Page: presta_cms.page.controller:renderAction
            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
#        templates_by_class:
#            Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: PrestaCMSCoreBundle:Page:index.html.twig

        routing_repositoryroot: /website/prestaconcept/route

knp_menu:
    twig: true

symfony_cmf_menu:
    menu_basepath: /website/prestaconcept/menu
    multilang:
      locales: %presta_admin.front.locales%

presta_cms_core:
  themes:
    default:
      name: default
      description: Presta CMS default theme
      template: PrestaCMSCoreBundle:Theme/Default:layout.html.twig
      screenshot: 'bundles/prestacmscore/themes/default/screenshot.jpg'
      zones:
        top_left:
          rows: 1
          cols: 6
          name: top_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
              is_editable: true
              is_deletable: false
              position: 10
        empty:
          rows: 1
          cols: 6
        navigation:
          rows: 1
          cols: 12
          name: navigation
          can_add_block: false
          can_sort_block: false
        content:
          rows: 4
          cols: 12
          name: content
          can_add_block: false
          can_sort_block: false
        footer_left:
          rows: 1
          cols: 6
          name: footer_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
              is_editable: true
              is_deletable: false
              position: 10
        footer_right:
          rows: 1
          cols: 6
          name: footer_right
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
              is_editable: true
              is_deletable: false
              position: 10
      page_template:
        default:
          name: default
          path: PrestaCMSCoreBundle:Theme/Default/Page:default.phtml.twig
          zones:
            content:
              rows: 1
              cols: 12
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
                  is_editable: true
                  is_deletable: false
                  position: 10
        sidebar:
          name: sidebar
          path: PrestaCMSCoreBundle:Theme/Default/Page:sidebar.phtml.twig
          zones:
            left:
              rows: 1
              cols: 2
              name: left
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
                  is_editable: true
                  is_deletable: false
                  position: 10
            content:
              rows: 1
              cols: 10
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: Presta\CMSCoreBundle\Document\Block\SimpleBlock
                  is_editable: true
                  is_deletable: false
                  position: 10


# CMF
#symfony_cmf_core:
#    document_manager: default
#    role``: IS_AUTHENTICATED_ANONYMOUSLY # used by the publish workflow checker

# app/config/config.yml
#symfony_cmf_content:
#    static_basepath: /content


sonata_doctrine_phpcr_admin:
    document_tree:
        Doctrine\PHPCR\Odm\Document\Generic:
            valid_children:
                - all
        Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: ~
        Symfony\Cmf\Bundle\RoutingExtraBundle\Document\Route:
            valid_children:
                - Symfony\Cmf\Bundle\RoutingExtraBundle\Document\Route
                - Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute
        Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:
            valid_children: []
        Symfony\Cmf\Bundle\MenuItem\Document\MenuItem:
            valid_children:
                - Symfony\Cmf\Bundle\MenuItem\Document\MenuItem
                - Symfony\Cmf\Bundle\ContentBundle\Document\MultilangMenuItem
        Symfony\Cmf\Bundle\ContentBundle\Document\MultilangMenuItem:
            valid_children:
                - Symfony\Cmf\Bundle\MenuItem\Document\MenuItem
                - Symfony\Cmf\Bundle\ContentBundle\Document\MultilangMenuItem
