imports:
    - { resource: '@PrestaAssetTinymceBundle/Resources/config/config.yml' }

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~

sonata_block:
  blocks:
    cms_core_editor:
    presta_cms.block.dashboard.cms:
    presta_cms.block.website.selector:

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_cms_core:
  themes:
    default:
      name: default
      description: Presta CMS default theme
      template: PrestaCMSCoreBundle:Theme/Default:layout.html.twig
      screenshot: 'bundles/prestacmscore/themes/default/screenshot.jpg'
      zones:
        top_left:
          rows: 1
          cols: 6
          name: top_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: cms_core_editor
              is_editable: true
              is_deletable: false
              position: 10
        empty:
          rows: 1
          cols: 6
        navigation:
          rows: 1
          cols: 12
          name: navigation
          can_add_block: false
          can_sort_block: false
        content:
          rows: 4
          cols: 12
          name: content
          can_add_block: false
          can_sort_block: false
        footer_left:
          rows: 1
          cols: 6
          name: footer_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: cms_core_editor
              is_editable: true
              is_deletable: false
              position: 10
        footer_right:
          rows: 1
          cols: 6
          name: footer_right
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              block_type: cms_core_editor
              is_editable: true
              is_deletable: false
              position: 10
      page_template:
        default:
          name: default
          path: PrestaCMSCoreBundle:Theme/Default/Page:default.phtml.twig
          zones:
            content:
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: cms_core_editor
                  is_editable: true
                  is_deletable: false
                  position: 10
        sidebar:
          name: sidebar
          path: PrestaCMSCoreBundle:Theme/Default/Page:sidebar.phtml.twig
          zones:
            left:
              name: left
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: cms_core_editor
                  is_editable: true
                  is_deletable: false
                  position: 10
            content:
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  block_type: cms_core_editor
                  is_editable: true
                  is_deletable: false
                  position: 10
