imports:
#     - { resource: '@PrestaAssetTinymceBundle/Resources/config/config.yml' }
     - { resource: 'theme_default.yml' }


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~


# Assetic Configuration
assetic:
    bundles:
        - PrestaCMSCoreBundle

sonata_block:
    blocks:
        presta_cms.block.dashboard.cms:
        presta_cms.block.website.selector:
        sonata_admin_doctrine_phpcr.tree_block:
        settings:
            id: '/cms'
            contexts:   [admin]

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_sonata_admin:
    menu:
        items:
            cms:
                route: presta_cms_page
                children:
                    websites:
                        route: admin_presta_cmscore_website_list
                    themes:
                        route: presta_cms_theme
                    pages:
                        route: presta_cms_page

symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            symfony_cmf_routing_extra.dynamic_router: 20
            router.default: 100
    dynamic:
        enabled: true
        controllers_by_alias:
            demo_alias: presta_cms.page.controller:aliasAction
        controllers_by_class:
            Presta\CMSCoreBundle\Document\Page: presta_cms.page.controller:renderAction
            Symfony\Cmf\Bundle\RoutingExtraBundle\Document\RedirectRoute:  symfony_cmf_routing_extra.redirect_controller:redirectAction
#        templates_by_class:
#            Symfony\Cmf\Bundle\ContentBundle\Document\MultilangStaticContent: PrestaCMSCoreBundle:Page:index.html.twig

#        routing_repositoryroot: /website/prestaconcept/route

knp_menu:
    twig: true

symfony_cmf_menu:
    menu_basepath: /website/prestaconcept/menu
    multilang:
      locales: %presta_admin.front.locales%

symfony_cmf_tree_browser:
    session_name:  default

fos_js_routing:
    routes_to_expose:
        - symfony_cmf_tree_browser.phpcr_children
        - symfony_cmf_tree_browser.phpcr_move
        - sonata.admin.doctrine_phpcr.phpcrodm_children
        - sonata.admin.doctrine_phpcr.phpcrodm_move
        - presta_cms_page_edit


# CMF
#symfony_cmf_core:
#    document_manager: default
#    role``: IS_AUTHENTICATED_ANONYMOUSLY # used by the publish workflow checker

# app/config/config.yml
#symfony_cmf_content:
#    static_basepath: /content


sonata_doctrine_phpcr_admin:
    confirm_move: true
    document_tree_defaults: [locale]
    document_tree:
        Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MenuNode
        Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode:
            valid_children:
                - Symfony\Cmf\Bundle\MenuBundle\Document\MultilangMenuNode
            image: '/bundles/symfonycmftreebrowser/images/document.png'

sonata_seo:
    encoding: UTF-8
    page:
        title: PrestaCMS by PrestaConcept


