imports:
     - { resource: '@PrestaAssetTinymceBundle/Resources/config/config.yml' }


doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationPrestaCMSCoreBundle: ~
                    PrestaCMSCoreBundle: ~

# Assetic Configuration
assetic:
    bundles:
        - PrestaCMSCoreBundle

sonata_block:
  blocks:
    cms_core_editor:
    presta_cms.block.dashboard.cms:
    presta_cms.block.website.selector:

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

