
#Administration - website
presta_cms_website:
    pattern:  /cms/website
    defaults: { _controller: PrestaCMSCoreBundle:Admin/Website:list, _sonata_admin: presta_cms.website.admin.website }
    
#Administration - themes
presta_cms_theme:
    pattern:  /cms/theme
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:list}
presta_cms_theme_edit:
    pattern:  /cms/theme/edit/{name}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit}
presta_cms_theme_website_edit:
    pattern:  /cms/theme/edit/{name}/website/{websiteId}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit}

presta_cms_theme_edit_block:
    pattern:  /cms/theme/block-edit/{websiteId}/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:edit, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        websiteId:  \d+
        id: \d+
presta_cms_theme_render_block:
    pattern:  /cms/theme/block-render/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:render, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        id: \d+
        
#Administration - pages
presta_cms_page:
    pattern:  /cms/page/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, id: '',  website_id: '', locale: ''}
presta_cms_page_edit:
    pattern:  /cms/page/edit/{id}/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, website_id: '', locale: ''}
    requirements:
        id: \d+
presta_cms_page_revision_edit_block:
    pattern:  /cms/page/block-edit/{website_id}/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:edit, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
    requirements:
        website_id:  \d+
        id: \d+        

presta_cms_page_revision_render_block:
    pattern:  /cms/page/block-render/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:render, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
    requirements:
        id: \d+

#Administration - Import / Export
presta_cms_page_selector:
    pattern:  /cms/page-selector/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:selector, website_id: '', locale: ''}

#Administration - Import / Export
presta_cms_data:
    pattern:  /cms/data/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Data:index, website_id: '', locale: ''}

