
#Administration - website
presta_cms_website:
    pattern:  /cms/website
    defaults: { _controller: PrestaCMSCoreBundle:Admin/Website:list, _sonata_admin: presta_cms.website.admin.website }

#Administration - themes
presta_cms_theme:
    pattern:  /cms/theme
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:list}
presta_cms_theme_edit:
    pattern:  /cms/theme/edit/{name}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit}
presta_cms_theme_website_edit:
    pattern:  /cms/theme/edit/{name}/website/{websiteId}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit}

presta_cms_block_edit:
    pattern:  /cms/block/edit/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:edit, _sonata_admin: presta_cms.admin.bloc}

presta_cms_block_render:
    pattern:  /cms/block/render/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:render, _sonata_admin: presta_cms.admin.bloc}

presta_cms_block_add:
    pattern:  /cms/block/add/{locale}/{origin}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:add, _sonata_admin: presta_cms.admin.bloc}
presta_cms_block_delete:
    pattern:  /cms/block/delete
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Block:delete, _sonata_admin: presta_cms.admin.bloc}

#Administration - pages
presta_cms_page:
    pattern:  /cms/page
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, websiteId: null, locale: null}
presta_cms_page_website:
    pattern:  /cms/page/website/{websiteId}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, websiteId: null, locale: null}
presta_cms_page_edit:
    pattern:  /cms/page/edit
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:edit}

#presta_cms_page_revision_edit_block:
#    pattern:  /cms/page/block-edit/{website_id}/{locale}/{id}
#    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:edit, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
#    requirements:
#        website_id:  \d+
#        id: \d+
#
#presta_cms_page_revision_render_block:
#    pattern:  /cms/page/block-render/{locale}/{id}
#    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:render, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
#    requirements:
#        id: \d+

#Administration - Import / Export
presta_cms_page_selector:
    pattern:  /cms/page-selector/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:selector, website_id: '', locale: ''}

#Administration - Import / Export
#presta_cms_data:
#    pattern:  /cms/data/{website_id}/{locale}
#    defaults: {_controller: PrestaCMSCoreBundle:Admin/Data:index, website_id: '', locale: ''}

fos_js_routing:
    resource: @FOSJsRoutingBundle/Resources/config/routing/routing.xml

