# IMPORTANT /!\ keep to the end (include a catch all)
#Front
#catchAll:
#    pattern:  /{path}
#    defaults: { _controller: PrestaCMSCoreBundle:Page:catchAll }
#    requirements:
#        path: .*