
#Administration
presta_cms_website:
    pattern:  /admin/cms/website
    defaults: { _controller: PrestaCMSCoreBundle:Admin/Website:list, _sonata_admin: presta_cms.website.admin.website }
presta_cms_page:
    pattern:  /admin/cms/page
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index}
presta_cms_theme:
    pattern:  /admin/cms/theme
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:list}
presta_cms_theme_edit:
    pattern:  /admin/cms/theme/edit/{name}/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit, website_id: '', locale: ''}
presta_cms_theme_edit_block:
    pattern:  /admin/cms/theme/block-edit/{website_id}/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:edit, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        website_id:  \d+
        id: \d+
presta_cms_theme_render_block:
    pattern:  /admin/cms/theme/block-render/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:render, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        id: \d+
#Front
catchAll:
    pattern:  /{_locale}/{path}
    defaults: { _controller: PrestaCMSCoreBundle:Page:catchAll }
    requirements:
        path: .*