
#Administration - website
presta_cms_website:
    pattern:  /admin/cms/website
    defaults: { _controller: PrestaCMSCoreBundle:Admin/Website:list, _sonata_admin: presta_cms.website.admin.website }
    
#Administration - themes
presta_cms_theme:
    pattern:  /admin/cms/theme
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:list}
presta_cms_theme_edit:
    pattern:  /admin/cms/theme/edit/{name}/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Theme:edit, website_id: '', locale: ''}
presta_cms_theme_edit_block:
    pattern:  /admin/cms/theme/block-edit/{website_id}/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:edit, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        website_id:  \d+
        id: \d+
presta_cms_theme_render_block:
    pattern:  /admin/cms/theme/block-render/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/ThemeBlock:render, id: '', _sonata_admin: 'presta_cms.theme.admin.bloc'}
    requirements:
        id: \d+
        
#Administration - pages
presta_cms_page:
    pattern:  /admin/cms/page/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, id: '',  website_id: '', locale: ''}
presta_cms_page_edit:
    pattern:  /admin/cms/page/edit/{id}/{website_id}/{locale}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/Page:index, website_id: '', locale: ''}
    requirements:
        id: \d+
presta_cms_page_revision_edit_block:
    pattern:  /admin/cms/page/block-edit/{website_id}/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:edit, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
    requirements:
        website_id:  \d+
        id: \d+        

presta_cms_page_revision_render_block:
    pattern:  /admin/cms/page/block-render/{locale}/{id}
    defaults: {_controller: PrestaCMSCoreBundle:Admin/PageRevisionBlock:render, id: '', _sonata_admin: 'presta_cms.page.admin.bloc'}
    requirements:
        id: \d+
#Front
catchAll:
    pattern:  /{path}
    defaults: { _controller: PrestaCMSCoreBundle:Page:catchAll }
    requirements:
        path: .*