parameters:
    cms_block_type:
      cms_core_editor: PrestaCMS\CoreBundle\Block\EditorBlockService
      cms_core_dummy: PrestaCMS\CoreBundle\Block\EditorBlockService
    cms_locales: {fr: fr, en: en}

services:
#    presta_cms_theme.example:
#        class: %presta_cms_theme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    #Configuration Menu
    presta_cms_core.configure_menu_listener:
        class: PrestaCMS\CoreBundle\EventListener\ConfigureMenuListener
        tags:
          - { name: kernel.event_listener, event: presta_admin.menu_configure, method: onMenuConfigure }
    
    #Admin class
    presta_cms.website.admin.website:
      class: PrestaCMS\CoreBundle\Admin\WebsiteAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: cms, label: website }
      arguments: [null, Application\PrestaCMS\CoreBundle\Entity\Website, PrestaCMSCoreBundle:Admin/Website]
      calls:
        - [ setAvailableLocales, [ %cms_locales% ] ]
    
    presta_cms.theme.admin.bloc:
      class: PrestaCMS\CoreBundle\Admin\BlockAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: cms, label: theme block }
      arguments: [null, Application\PrestaCMS\CoreBundle\Entity\ThemeBlock, PrestaCMSCoreBundle:Admin/ThemeBlock]
      calls:
        - [ setBlockManager, [ @sonata.block.manager ] ]
      
    #CMS Block service
    cms_core_editor:
      class: PrestaCMS\CoreBundle\Block\EditorBlockService
      tags:
        - {name: sonata.block}
      arguments: [cms_core_editor, @templating]
    
    #Block service
    presta_cms.block.dashboard.cms:
      class: PrestaCMS\CoreBundle\Block\Dashboard\CmsBlockService
      tags:
        - {name: sonata.block}
      arguments: [presta_cms.block.dashboard.cms, @templating, @sonata.admin.pool]
    presta_cms.block.website.selector:
      class: PrestaCMS\CoreBundle\Block\WebsiteSelectorService
      tags:
        - {name: sonata.block}
      arguments: [presta_cms.block.website.selector, @templating, @presta_cms.website_manager]
      
    #Manager
    presta_cms.website_manager:
      class: PrestaCMS\CoreBundle\Model\WebsiteManager
      arguments: [@service_container]
    presta_cms.theme_manager:
      class: PrestaCMS\CoreBundle\Model\ThemeManager
      arguments: [@service_container]
    presta_cms.page_manager:
      class: PrestaCMS\CoreBundle\Model\PageManager
      arguments: [@service_container]
      