presta_cms_core:
  themes:
    default:
      name: default
      description: Presta CMS default theme
      navigations: [main]
      template: PrestaCMSCoreBundle:Theme/Default:layout.html.twig
      screenshot: 'bundles/prestacmscore/themes/default/screenshot.jpg'
      zones:
        top_left:
          rows: 1
          cols: 6
          name: top_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              name: main
              type: presta_cms.block.simple
              is_editable: true
              is_deletable: false
              position: 10
        empty:
          rows: 1
          cols: 6
        navigation:
          rows: 1
          cols: 12
          name: navigation
          can_add_block: false
          can_sort_block: false
        content:
          rows: 4
          cols: 12
          name: content
          can_add_block: false
          can_sort_block: false
        footer_left:
          rows: 1
          cols: 6
          name: footer_left
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              type: presta_cms.block.simple
              is_editable: true
              is_deletable: false
              position: 10
        footer_right:
          rows: 1
          cols: 6
          name: footer_right
          can_add_block: false
          can_sort_block: false
          blocks:
            editor:
              type: presta_cms.block.simple
              is_editable: true
              is_deletable: false
              position: 10
      page_template:
        default:
          name: default
          path: PrestaCMSCoreBundle:Theme/Default/Page:default.phtml.twig
          zones:
            content:
              rows: 1
              cols: 12
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  type: presta_cms.block.simple
                  is_editable: true
                  is_deletable: false
                  position: 10
        sidebar:
          name: sidebar
          path: PrestaCMSCoreBundle:Theme/Default/Page:sidebar.phtml.twig
          zones:
            left:
              rows: 1
              cols: 2
              name: left
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  type: presta_cms.block.simple
                  is_editable: true
                  is_deletable: false
                  position: 10
            content:
              rows: 1
              cols: 10
              name: content
              can_add_block: false
              can_sort_block: false
              blocks:
                editor:
                  type: presta_cms.block.simple
                  is_editable: true
                  is_deletable: false
                  position: 10
