language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - wget http://getcomposer.org/composer.phar
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - cp ./Tests/Functional/config/parameters.yml.dist ./Tests/Functional/config/parameters.yml
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh


script:
  - phpunit --coverage-text
  - phpcs --ignore=/vendor/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .


notifications:
  email: "nbastien@prestaconcept.net"
